VERSION 1
ID 137
REFERENCE JKPLUSINGAME
COUNT 2
INDEX 0
{
   REFERENCE CLIENT_PLUGIN
   TEXT_LANGUAGE1 "Client Plugin"
   TEXT_LANGUAGE2 "Plugin Client"
   TEXT_LANGUAGE3 "Client Plugin"
   TEXT_LANGUAGE6 "Client Plugin"
   TEXT_LANGUAGE8 "Plugin Cliente"
}
INDEX 1
{
   REFERENCE SPEED_O_METER_LABEL
   TEXT_LANGUAGE1 "Speed"
   TEXT_LANGUAGE2 "Vitesse"
   TEXT_LANGUAGE3 "Schnelle"
   TEXT_LANGUAGE6 "Speed"
   TEXT_LANGUAGE8 "Velocidad"
}
