VERSION 1
ID 137
REFERENCE JKINGAME
COUNT 1
INDEX 0
{
   REFERENCE RACE_TIME
   TEXT_LANGUAGE1 "Time"
   TEXT_LANGUAGE2 "Temps"
   TEXT_LANGUAGE3 "Zeit"
   TEXT_LANGUAGE6 "Time"
   TEXT_LANGUAGE8 "Tiempo"
}
