VERSION 1
ID 137
REFERENCE JKINGAME
COUNT 3
INDEX 0
{
   REFERENCE RACE_TIME
   TEXT_LANGUAGE1 "Time"
   TEXT_LANGUAGE2 "Temps"
   TEXT_LANGUAGE3 "Zeit"
   TEXT_LANGUAGE6 "Time"
   TEXT_LANGUAGE8 "Tiempo"
}
INDEX 1
{
   REFERENCE PAUSE_GAME
   TEXT_LANGUAGE1 "Game paused"
   TEXT_LANGUAGE2 "Jeu en pause"
   TEXT_LANGUAGE3 "Spiel pausiert"
   TEXT_LANGUAGE6 "Game paused"
   TEXT_LANGUAGE8 "Juego pausado"
}
INDEX 2
{
   REFERENCE PAUSE_GAME_SEC
   TEXT_LANGUAGE1 "Resume in %i"
   TEXT_LANGUAGE2 "Reprise dans %i"
   TEXT_LANGUAGE3 "Wieder aufnehmen %i"
   TEXT_LANGUAGE6 "Resume in %i"
   TEXT_LANGUAGE8 "Reanudando en %i"
}
